name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  avatar_stack: ^3.0.0
  badges: ^3.2.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_slidable: ^4.0.3
  get: ^4.7.3
  google_fonts: ^8.1.0
  intl: ^0.20.2
  lottie: ^3.3.3
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.5
  shimmer: ^3.0.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
